# Form implementation generated from reading ui file 'ui\login_page.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(602, 596)
        self.RegisterUser_2 = QtWidgets.QPushButton(parent=Form)
        self.RegisterUser_2.setGeometry(QtCore.QRect(230, 420, 111, 30))
        self.RegisterUser_2.setObjectName("RegisterUser_2")
        self.UsernameLabel_2 = QtWidgets.QLabel(parent=Form)
        self.UsernameLabel_2.setGeometry(QtCore.QRect(234, 245, 111, 31))
        self.UsernameLabel_2.setObjectName("UsernameLabel_2")
        self.LogIn_2 = QtWidgets.QPushButton(parent=Form)
        self.LogIn_2.setGeometry(QtCore.QRect(235, 380, 104, 30))
        self.LogIn_2.setObjectName("LogIn_2")
        self.UsernameEntryBox_2 = QtWidgets.QLineEdit(parent=Form)
        self.UsernameEntryBox_2.setGeometry(QtCore.QRect(226, 281, 131, 22))
        self.UsernameEntryBox_2.setText("")
        self.UsernameEntryBox_2.setObjectName("UsernameEntryBox_2")
        self.DCMTitle_2 = QtWidgets.QLabel(parent=Form)
        self.DCMTitle_2.setEnabled(True)
        self.DCMTitle_2.setGeometry(QtCore.QRect(40, 100, 521, 111))
        font = QtGui.QFont()
        font.setPointSize(23)
        font.setBold(False)
        self.DCMTitle_2.setFont(font)
        self.DCMTitle_2.setObjectName("DCMTitle_2")
        self.PasswordLabel_2 = QtWidgets.QLabel(parent=Form)
        self.PasswordLabel_2.setGeometry(QtCore.QRect(234, 305, 111, 31))
        self.PasswordLabel_2.setObjectName("PasswordLabel_2")
        self.PasswordEntryBox_2 = QtWidgets.QLineEdit(parent=Form)
        self.PasswordEntryBox_2.setGeometry(QtCore.QRect(224, 340, 130, 22))
        self.PasswordEntryBox_2.setText("")
        self.PasswordEntryBox_2.setObjectName("PasswordEntryBox_2")
        self.LoginError = QtWidgets.QLabel(parent=Form)
        self.LoginError.setGeometry(QtCore.QRect(196, 460, 180, 20))
        self.LoginError.setText("")
        self.LoginError.setTextFormat(QtCore.Qt.TextFormat.PlainText)
        self.LoginError.setObjectName("LoginError")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.RegisterUser_2.setText(_translate("Form", "Register New User"))
        self.UsernameLabel_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Username</span></p></body></html>"))
        self.LogIn_2.setText(_translate("Form", "Login"))
        self.DCMTitle_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt;\">DCM Interface</span></p></body></html>"))
        self.PasswordLabel_2.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Password</span></p></body></html>"))
